name: Discord Notification Filter
on:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Send Discord Webhook
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        PR_STATUS: ${{ github.event.action }}
        PR_MERGED: ${{ github.event.pull_request.merged }}
        PR_TITLE: ${{ github.event.pull_request.title }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        PR_URL: ${{ github.event.pull_request.html_url }}
        PR_USER: ${{ github.actor }}
        REPO_NAME: ${{ github.repository }}
      run: |
          COLOR_OPENED=3066993  # Blue
          COLOR_MERGED=7291585  # Merged color
          COLOR_CLOSED=15158332 # Red (closed)
        
          SELECTED_COLOR=$COLOR_OPENED
          
          if [ "$PR_STATUS" == "closed" ]; then
            if [ "$PR_MERGED" == "true" ]; then
              SELECTED_COLOR=$COLOR_MERGED
              PR_STATUS="merged"
            else
              SELECTED_COLOR=$COLOR_CLOSED
            fi
          fi
          
          PAYLOAD=$(jq -n \
            --arg title "GitHub #$PR_NUMBER - $PR_STATUS: $PR_TITLE" \
            --arg url "$PR_URL" \
            --arg color "$SELECTED_COLOR" \
            --arg author "$PR_USER" \
            --arg repo "$REPO_NAME" \
            '{
              embeds: [{
                title: $title,
                url: $url,
                color: ($color | tonumber),
                fields: [
                  { name: "Autor", value: $author, inline: true },
                  { name: "Repositório", value: $repo, inline: true }
                ],
                footer: { text: "GitHub Actions" }
              }]
            }')
          
          curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" $DISCORD_WEBHOOK